USE BlindTrial;
SET NOCOUNT ON; SET STATISTICS IO ON; SET STATISTICS TIME ON;
DECLARE @sink1 int, @sink2 int;
PRINT '=== D1 usp_OrdersByChannelDate (before) ===';
EXEC dbo.usp_OrdersByChannelDate 'WEB', '2025-03-01', '2025-03-08';
PRINT '=== D1 after (index in rolled-back tran) ===';
BEGIN TRAN; CREATE INDEX IX_fix ON dbo.Orders (Channel, OrderDate) INCLUDE (CustomerID, TotalAmount);
EXEC dbo.usp_OrdersByChannelDate 'WEB', '2025-03-01', '2025-03-08' WITH RECOMPILE; ROLLBACK;
PRINT '=== D7 usp_CustomerByEmail (LOWER) ===';
EXEC dbo.usp_CustomerByEmail 'user12345@example3.com';
PRINT '=== D7 sargable equivalent ===';
SELECT CustomerID, Email, Region, Tier FROM dbo.Customers WHERE Email = 'user12345@example3.com';
PRINT '=== D8 usp_ProductSearch ===';
EXEC dbo.usp_ProductSearch 'Gizmo 4999';
PRINT '=== D9 usp_ShipmentByTracking (nvarchar) ===';
EXEC dbo.usp_ShipmentByTracking N'TRK000000700000A';
PRINT '=== B5 usp_ShipmentByTrackingTyped (varchar) ===';
EXEC dbo.usp_ShipmentByTrackingTyped 'TRK000000700000A';
PRINT '=== D10 usp_OrdersWithTier (UDF) ===';
EXEC dbo.usp_OrdersWithTier '2024-08-01', '2026-08-01';
PRINT '=== D10 inline equivalent ===';
SELECT o.OrderID, o.CustomerID, CASE c.Tier WHEN 1 THEN 'BRONZE' WHEN 2 THEN 'SILVER' WHEN 3 THEN 'GOLD' ELSE 'PLATINUM' END, o.TotalAmount
FROM dbo.Orders o JOIN dbo.Customers c ON c.CustomerID=o.CustomerID WHERE o.OrderID BETWEEN 1 AND 50000 AND o.OrderDate >= '2024-08-01' AND o.OrderDate < '2026-08-01';
PRINT '=== D11 sniff: CANCELLED first (fresh plan) ===';
EXEC sp_recompile 'dbo.usp_OrdersByStatus';
EXEC dbo.usp_OrdersByStatus 'CANCELLED';
PRINT '=== D11 sniff: SHIPPED reusing CANCELLED plan ===';
EXEC dbo.usp_OrdersByStatus 'SHIPPED';
PRINT '=== D11 sniff: SHIPPED with its own plan ===';
EXEC sp_recompile 'dbo.usp_OrdersByStatus';
EXEC dbo.usp_OrdersByStatus 'SHIPPED';
PRINT '=== D12 usp_CustomerOrderSummary (no FK index) ===';
EXEC dbo.usp_CustomerOrderSummary 777;
PRINT '=== D12 after (index in rolled-back tran) ===';
BEGIN TRAN; CREATE INDEX IX_fix2 ON dbo.Orders (CustomerID) INCLUDE (TotalAmount);
EXEC dbo.usp_CustomerOrderSummary 777 WITH RECOMPILE; ROLLBACK;
PRINT '=== D13 usp_EventDump (SELECT * ORDER BY Payload) ===';
EXEC dbo.usp_EventDump '2026-05-01';
PRINT '=== D14 usp_DashboardTotals ===';
EXEC dbo.usp_DashboardTotals;
PRINT '=== D15 cursor (2000 pending changes) ===';
INSERT dbo.PriceChanges (ProductID, NewPrice) SELECT n, 9.99 FROM dbo.vNums WHERE n <= 2000;
EXEC dbo.usp_ApplyPriceChanges;
PRINT '=== D15 set-based equivalent (rolled back) ===';
INSERT dbo.PriceChanges (ProductID, NewPrice) SELECT n, 9.99 FROM dbo.vNums WHERE n <= 2000;
BEGIN TRAN;
UPDATE p SET Price = pc.NewPrice FROM dbo.Products p JOIN dbo.PriceChanges pc ON pc.ProductID = p.ProductID WHERE pc.Applied = 0;
UPDATE dbo.PriceChanges SET Applied = 1 WHERE Applied = 0;
ROLLBACK; DELETE dbo.PriceChanges WHERE Applied = 0;
PRINT '=== D18c usp_TopProductsInCategory ===';
EXEC dbo.usp_TopProductsInCategory 5;
PRINT '=== B4 usp_CategoryByName ===';
EXEC dbo.usp_CategoryByName 'Category 7';
PRINT '=== B1 usp_DatabaseInventory ===';
EXEC dbo.usp_DatabaseInventory;
